model = dict(
    type='UnifiedModel',
    vggish=dict(
        freeze_audio_extractor=True,
        pretrained_vggish_model_path='pretrained/vggish-10086976.pth',
        preprocess_audio_to_log_mel=False,
        postprocess_log_mel_with_pca=False,
        pretrained_pca_params_path=None),
    backbone=dict(
        type='UniPerceiverAdapter',
        patch_size=16,
        embed_dim=768,
        depth=12,
        num_heads=12,
        mlp_ratio=4,
        drop_path_rate=0.2,
        conv_inplane=64,
        n_points=4,
        deform_num_heads=12,
        cffn_ratio=0.25,
        deform_ratio=0.5,
        num_classes=1,
        with_cp=True,
        out_indices=(1, 2, 3),
        interaction_indexes=[[0, 2], [3, 5], [6, 8], [9, 11]],
        window_attn=[True]*12,
        window_size=[14]*12,
        pretrained='pretrained/uni-perceiver-base-L12-H768-224size-torch-pretrained_converted.pth'),
    neck=dict(
        type='ChannelMapper',
        in_channels=[768, 768, 768],
        kernel_size=1,
        out_channels=256,
        act_cfg=None,
        norm_cfg=dict(type='GN', num_groups=32),
        num_outs=4),
    head=dict(
        type='UMHead',
        num_classes=1,
        query_num=300,
        use_learnable_queries=True,
        # fusion_block=dict(type='CrossModalMixer'),
        positional_encoding=dict(
            type='SinePositionalEncoding',
            num_feats=128),
        transformer=dict(
            type='AVSTransformer',
            encoder=dict(
                num_layers=6,
                layer=dict(
                    dim=256,
                    ffn_dim=2048,
                    dropout=0.1)),
            decoder=dict(
                num_layers=6,
                layer=dict(
                    dim=256,
                    ffn_dim=2048,
                    dropout=0.1)))),
    audio_dim=128,
    embed_dim=768,
    freeze_audio_backbone=True,
    T=5)
dataset = dict(
    train=dict(
        type='S4Dataset',
        split='train',
        anno_csv='data/Single-source/s4_meta_data.csv',
        dir_img='data/Single-source/s4_data/visual_frames',
        dir_audio_log_mel='data/Single-source/s4_data/audio_log_mel',
        dir_mask='data/Single-source/s4_data/gt_masks',
        img_size=[224, 224],
        batch_size=2),
    val=dict(
        type='S4Dataset',
        split='val',
        anno_csv='data/Single-source/s4_meta_data.csv',
        dir_img='data/Single-source/s4_data/visual_frames',
        dir_audio_log_mel='data/Single-source/s4_data/audio_log_mel',
        dir_mask='data/Single-source/s4_data/gt_masks',
        img_size=[224, 224],
        batch_size=2),
    test=dict(
        type='S4Dataset',
        split='test',
        anno_csv='data/Single-source/s4_meta_data.csv',
        dir_img='data/Single-source/s4_data/visual_frames',
        dir_audio_log_mel='data/Single-source/s4_data/audio_log_mel',
        dir_mask='data/Single-source/s4_data/gt_masks',
        img_size=[224, 224],
        batch_size=2))
optimizer = dict(
    type='AdamW',
    lr=2e-5)
loss = dict(
    weight_dict=dict(
        iou_loss=1.0,
        mix_loss=0.1),
    loss_type='dice')
process = dict(
    num_works=8,
    train_epochs=30,
    freeze_epochs=5)
